### ISSUE TITLE
Stat enhancements

### ISSUE THREAD

**Issue by paulsnoops** [pnxenopoulos/awpy#182]
It would be nice to be able to see a player's stats as follows:

- Amount of rounds with 0 kill, 1 kill, 2 kills, 3 kills, 4 kills, 5 kills
- Clutches: amount of rounds where a player had a clutch for each of 1v1, 1v2, 1v3, 1v4, 1v5 and how successful they were; as an example player A had 4 rounds where they were 1v3 and won 50% of those clutches (another example in pic 1 below)
- I think we can already see how many trade kills a player had but what about how many times they were traded by another player?
- Player saved by teammates/Player saved teammates, both the amounts and per round (as seen in picture 2 like on HLTV)

**Pic 1**
![image](https://user-images.githubusercontent.com/18243520/183278891-5d329004-cb0a-467d-b1d2-35a0ac2b17d9.png)

**Pic 2**
![image](https://user-images.githubusercontent.com/18243520/183278832-42f4493e-f78e-431b-bc48-f0d1c4310cb9.png)

I realise some of this may be difficult to implement so no worries if they aren't added :)
Thank you

**Comment by JanEricNitschke** [comment]
I think multi-kill rounds are probably easy to track and add to the player statistics function.

Clutches are probably also possible but slightly harder.

I think traded is actually trivial since it is already effectively being monitored for KAST.

I dont know about saving/being saved. There might actually be an event in the demo file since this is broadcasted in chat in MM right? If not then one would need to chose how to define that.

If you are interested you could probably try to implement some of these here: https://github.com/pnxenopoulos/awpy/blob/main/awpy/analytics/stats.py

**Comment by JanEricNitschke** [comment]
Most of these things have been implemented with https://github.com/pnxenopoulos/awpy/commit/142583e72d2de9990a3271663e6bfe0d69784164#diff-298f0bf26aaad42c9c163f69bba432beedac14f685c6c593957e46ae344ab480R81

I think the only thing missing would be player saved.

**Comment by paulsnoops** [comment]
Thanks @JanEricNitschke :) I'm not too bothered about the save stat to be honest so unless you guys want it, this issue can be closed?

**Comment by pnxenopoulos** [comment]
@paulsnoops Will close for now. You know where to find us if something doesn't work or if a feature crosses your mind :)
