### ISSUE TITLE
CEVO POV demo parses with empty gameRounds

### ISSUE THREAD

**Issue by JacobPalecki** [pnxenopoulos/awpy#284]
**Describe the bug**
POV demo from CEVO match in 2017 parses with empty gameRounds.

**Include Information to Reproduce**
Link to demo: [https://www.dropbox.com/scl/fi/51t9cnhflwz07hs30oxz3/gt.dem?rlkey=hymp1g8nj1qo37jdugwrarxkp&dl=0](https://www.dropbox.com/scl/fi/51t9cnhflwz07hs30oxz3/gt.dem?rlkey=hymp1g8nj1qo37jdugwrarxkp&dl=0)
Code:
`
from awpy.parser import DemoParser

demo_parser = DemoParser(
    demofile = "gt.dem", 
    demo_id = "gt", 
    parse_rate=128, 
    trade_time=5, 
    buy_style="hltv",
    clean=False
)

data = demo_parser.parse()
`

**Screenshots**
![image](https://github.com/pnxenopoulos/awpy/assets/16246195/9a3f240f-07a9-437f-a0b7-6174de2d604a)

**Additional context**
On latest awpy 1.3.1 and python 3.11.5

**Comment by JanEricNitschke** [comment]
Hi, thanks for the issue.

POV demos are a bit difficult for awpy as they are missing a bunch of information. Specifically they are basically always missing the opposing team and sometimes even general information or events.

That can cause issues with the parsing logic but more frequently is causes issue with the cleaning of rounds that throws away warmups, knife rounds and such.

If you run it with `data = demo_parser.parse(clean=False)` instead then you will get the rounds.

This means that the cleaning throws away all of the rounds. I will check if there is something reasonable we can do that avoids this issue, however i can not guarentee that because this is a heuristic thing anyway and POV demos are in general a small use case.

If there is nothing general we can/will do you can try to customize the cleaning process by running

```
demo_parser.parse(clean=False)
data = demo_parser.clean_rounds(remove_bad_scoring=False, save_to_json=True)
```

And you can check [here](https://github.com/pnxenopoulos/awpy/blob/main/awpy/parser/demoparser.py#L851) what cleaning steps are available. If that does not work you would have to implement your own cleaning logic.

**Comment by JanEricNitschke** [comment]
Ok, so it seems that the issue is actually just due to the warmup cleaning logic. That seems to remove basically all rounds.

Will investigate this further but i feel that this is fixable.

**Comment by pnxenopoulos** [comment]
Hey @JacobPalecki -- thanks for creating this issue. We're close to fixing it. Do you mind if we keep your demofile in our test suite going forward to ensure we can always parse these kinds of demos?

**Comment by JacobPalecki** [comment]
I do not mind.
Please let me know when you have fixed it, as I'd love to try it out.

**Comment by JanEricNitschke** [comment]
Hi @JacobPalecki 
the issue should now be fixed on the current main branch.

If you grab awpy from there it should now work. Alternatively you can wait for a new release on pypi or add the changes we made (https://github.com/pnxenopoulos/awpy/pull/286) locally. The main offender was the warmup cleaning.
